"""
Pydantic schemas for request validation and response serialisation.

All public API data contracts live here so they can be imported
by routes, agents, and services without circular dependencies.
"""

from __future__ import annotations

from typing import Literal, Optional
from pydantic import BaseModel, Field, field_validator


# ─────────────────────────────────────────────────────────────────────────────
#  Enumerations (expressed as Literal types for Pydantic v2 compatibility)
# ─────────────────────────────────────────────────────────────────────────────

IntentType = Literal[
    "Donation",
    "Volunteer",
    "Complaint",
    "Emergency Help",
    "General Inquiry",
]

UrgencyType = Literal["High", "Medium", "Low"]

RouteType = Literal[
    "human_agent",
    "finance_team",
    "volunteer_team",
    "general_support",
]


# ─────────────────────────────────────────────────────────────────────────────
#  API Request
# ─────────────────────────────────────────────────────────────────────────────


class TriageRequest(BaseModel):
    """Incoming payload for the POST /triage endpoint."""

    message: str = Field(
        ...,
        min_length=3,
        max_length=4000,
        description="The raw user support message to be triaged.",
        examples=["Hi, I want to donate $500 to your flood relief fund."],
    )
    session_id: Optional[str] = Field(
        default=None,
        description="Optional session identifier for conversation memory.",
    )

    @field_validator("message")
    @classmethod
    def strip_message(cls, v: str) -> str:
        return v.strip()


# ─────────────────────────────────────────────────────────────────────────────
#  Intermediate Agent Outputs
# ─────────────────────────────────────────────────────────────────────────────


class ClassificationResult(BaseModel):
    """Output produced by the Classifier Agent."""

    intent: IntentType = Field(
        default="General Inquiry",
        description="Detected intent category.",
    )
    urgency: UrgencyType = Field(
        default="Low",
        description="Assessed urgency level.",
    )


class EntityModel(BaseModel):
    """Structured named entities extracted by the NER Agent."""

    full_name: str = Field(default="", description="Full name of the sender.")
    phone_number: str = Field(default="", description="Contact phone number.")
    email: str = Field(default="", description="Contact email address.")
    location: str = Field(default="", description="Geographical location mentioned.")
    case_id: str = Field(default="", description="Reference case or ticket ID.")
    date: str = Field(default="", description="Any date mentioned in the message.")


class DecisionResult(BaseModel):
    """Output produced by the Decision/Routing Agent."""

    route: RouteType = Field(
        default="general_support",
        description="Department or queue to route the request to.",
    )
    escalated: bool = Field(
        default=False,
        description="True when the request is escalated to a human agent.",
    )
    priority: UrgencyType = Field(
        default="Low",
        description="Priority level used for queue ordering.",
    )


# ─────────────────────────────────────────────────────────────────────────────
#  Conversation Memory
# ─────────────────────────────────────────────────────────────────────────────


class ConversationTurn(BaseModel):
    """A single user–assistant exchange stored in session memory."""

    role: Literal["user", "assistant"]
    content: str


# ─────────────────────────────────────────────────────────────────────────────
#  API Response
# ─────────────────────────────────────────────────────────────────────────────


class TriageResponse(BaseModel):
    """Full response returned by the POST /triage endpoint."""

    intent: str = Field(description="Classified intent of the message.")
    urgency: str = Field(description="Assessed urgency level.")
    entities: EntityModel = Field(description="Named entities extracted from the message.")
    response: str = Field(description="Empathetic, human-like reply generated by the AI.")
    route: str = Field(description="Internal team or queue the request is routed to.")
    escalated: bool = Field(default=False, description="Whether the request was escalated.")
    session_id: Optional[str] = Field(default=None, description="Echo of the session ID if provided.")

    class Config:
        json_schema_extra = {
            "example": {
                "intent": "Donation",
                "urgency": "Low",
                "entities": {
                    "full_name": "Sarah Johnson",
                    "phone_number": "",
                    "email": "sarah@example.com",
                    "location": "Chicago",
                    "case_id": "",
                    "date": "",
                },
                "response": "Thank you so much, Sarah! Your generous donation truly makes a difference...",
                "route": "finance_team",
                "escalated": False,
                "session_id": None,
            }
        }


# ─────────────────────────────────────────────────────────────────────────────
#  Health Check
# ─────────────────────────────────────────────────────────────────────────────


class HealthResponse(BaseModel):
    """Response from the GET /health endpoint."""

    status: str = "ok"
    version: str = "1.0.0"
    environment: str = "development"
